### ISSUE TITLE
Edit to the README.md

### ISSUE THREAD

**Issue by SyiCon** [asaladino/ethos-endpoint-checker-java#5]
I made 2 edits to the instructions.  1)  about removing the onlyCheck to run all endpoints and 2) instructions on editing the jar file name.

![README_edits](https://user-images.githubusercontent.com/19938383/66048966-88d20b80-e4f8-11e9-9480-d6595b885ca2.jpg)

**Comment by asaladino** [comment]
Readme has been updated.
